# Generated by Django 3.0.8 on 2020-09-22 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 9, 24, 15, 342162, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='project_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
