# Generated by Django 3.0.8 on 2020-10-06 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 10, 49, 17, 926772, tzinfo=utc)),
        ),
    ]
