# Generated by Django 3.0.8 on 2020-09-22 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200922_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 10, 1, 27, 17270, tzinfo=utc)),
        ),
    ]
