# Generated by Django 3.0.8 on 2020-10-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201006_0758'),
        ('users', '0007_auto_20201006_1149'),
    ]

    operations = [
    ]
