# Generated by Django 3.0.8 on 2020-10-06 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201006_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 13, 21, 49, 874867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 13, 21, 49, 849392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 13, 21, 49, 849444, tzinfo=utc)),
        ),
    ]
