# Generated by Django 3.0.8 on 2020-10-06 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201006_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 11, 17, 51, 146963, tzinfo=utc)),
        ),
    ]
