# Generated by Django 3.0.8 on 2020-10-06 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201006_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 11, 41, 25, 361396, tzinfo=utc)),
        ),
    ]
