# Generated by Django 3.0.8 on 2020-10-06 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201006_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 11, 43, 1, 708154, tzinfo=utc)),
        ),
    ]
