# Generated by Django 3.0.8 on 2020-10-02 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201002_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='num_supporters',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 6, 46, 3, 879591, tzinfo=utc)),
        ),
    ]
