# Generated by Django 3.0.8 on 2020-10-02 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201002_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 6, 53, 12, 637686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 6, 53, 12, 637715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_supporters',
            field=models.IntegerField(default=0),
        ),
    ]
