# Generated by Django 3.0.8 on 2020-10-02 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201002_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='num_supporters',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 7, 0, 43, 457739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 7, 0, 43, 457767, tzinfo=utc)),
        ),
    ]
