# Generated by Django 3.0.8 on 2020-10-02 11:26

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20201002_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_supporters',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 25, 52, 28083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 25, 52, 28141, tzinfo=utc)),
        ),
    ]
