# Generated by Django 3.0.8 on 2020-10-02 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20201002_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 50, 30, 678415, tzinfo=utc)),
        ),
    ]
